name: Run Selenium Tests & View Allure Reports

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
          echo "Detected Chrome version: $CHROME_VERSION"
          DRIVER_VERSION=""
          for i in {1..5}; do
            DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION) && break
            echo "Retrying ChromeDriver version fetch..."
            sleep 2
          done
          if [[ -z "$DRIVER_VERSION" ]]; then
            echo "Failed to retrieve ChromeDriver version"
            exit 1
          fi
          echo "Installing ChromeDriver version: $DRIVER_VERSION"
          wget -q --retry-connrefused --waitretry=2 --tries=5 \
            "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          chmod +x /usr/local/bin/chromedriver

      - name: Set Chrome Permissions
        run: sudo chmod 777 /usr/bin/google-chrome

      - name: Run Tests with Headless Chrome
        run: mvn clean test -DargLine="--enable-preview"

      - name: Run Tests with Preview Features
        run: mvn clean test -Dmaven.compiler.release=21 -Dmaven.compiler.showWarnings=true -DargLine="--enable-preview"

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Manually Clone Upload-Artifact
        run: |
          mkdir -p $GITHUB_WORKSPACE/actions
          cd $GITHUB_WORKSPACE/actions
          git clone https://github.com/actions/upload-artifact.git

      - name: Upload Allure Report as Artifact
        uses: ./actions/upload-artifact
        with:
          name: allure-report
          path: target/site/allure-maven/
          if-no-files-found: warn

  deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven/

      - name: Deploy Allure Report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/site/allure-maven/