name: Run Selenium Tests & Deploy Allure Reports

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
          install-chromedriver: true

      - name: Install Allure Plugin
        run: mvn org.apache.maven.plugins:maven-plugin-plugin:3.6.0:help

      - name: Run Tests with Headless Chrome
        run: mvn clean test -DargLine="--enable-preview"

      - name: Generate Allure Report
        run: |
          if [ -d "target/allure-results" ]; then
            echo "Generating Allure report..."
            mvn io.qameta.allure:allure-maven:report
            mkdir -p target/site/allure-maven/  # Ensure directory exists before deployment
          else
            echo "Skipping Allure report generation: No test results found."
          fi

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/site/allure-maven/