name: Run Selenium Tests & View Allure Reports

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Latest Chrome & Matching ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip jq

          # Install latest stable Chrome
          sudo apt install -y google-chrome-stable

          # Get full Chrome version
          FULL_CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=$(echo "$FULL_CHROME_VERSION" | cut -d. -f1)
          echo "Installed Chrome version: $FULL_CHROME_VERSION (Major: $CHROME_MAJOR_VERSION)"

          # Fetch matching ChromeDriver version using Google's API
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.versions[] | select(.version | startswith(\"$FULL_CHROME_VERSION\")) | .version" | head -n 1)

          if [[ -z "$DRIVER_VERSION" || "$DRIVER_VERSION" == "null" ]]; then
            echo "No exact match for ChromeDriver version found. Falling back to latest stable version."
            DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi

          echo "Installing ChromeDriver version: $DRIVER_VERSION"
          DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.versions[] | select(.version == \"$DRIVER_VERSION\") | .downloads.chromeDriver[] | select(.platform == \"linux64\") | .url")

          if [[ -z "$DRIVER_URL" || "$DRIVER_URL" == "null" ]]; then
            echo "Failed to fetch ChromeDriver download URL. Exiting."
            exit 1
          fi

          wget -q "$DRIVER_URL" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          chmod +x /usr/local/bin/chromedriver

      - name: Set Chrome Permissions
        run: sudo chmod 777 /usr/bin/google-chrome

      - name: Run Tests with Headless Chrome
        run: mvn clean test -DargLine="--enable-preview"

      - name: Run Tests with Preview Features
        run: mvn clean test -Dmaven.compiler.release=21 -Dmaven.compiler.showWarnings=true -DargLine="--enable-preview"

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Manually Clone Upload-Artifact
        run: |
          mkdir -p $GITHUB_WORKSPACE/actions
          cd $GITHUB_WORKSPACE/actions
          git clone https://github.com/actions/upload-artifact.git

      - name: Upload Allure Report as Artifact
        uses: ./actions/upload-artifact
        with:
          name: allure-report
          path: target/site/allure-maven/
          if-no-files-found: warn

  deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven/

      - name: Deploy Allure Report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/site/allure-maven/