name: Run Selenium Tests & View Allure Reports

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
          install-chromedriver: true

      - name: Run Tests with Headless Chrome
        run: mvn clean test -DargLine="--enable-preview"

      - name: Debug - Check Allure Report Directory
        run: |
          ls -la target/site/allure-maven/

      - name: Generate Allure Report
        run: |
          mvn allure:report || echo "Allure report generation failed"

      - name: Manually Clone Upload-Artifact
        run: |
          mkdir -p $GITHUB_WORKSPACE/actions
          cd $GITHUB_WORKSPACE/actions
          git clone https://github.com/actions/upload-artifact.git

      - name: Upload Allure Report as Artifact
        uses: ./actions/upload-artifact
        with:
          name: allure-report
          path: target/site/allure-maven/